let products = [
    {
        id: "a1",
        name: "Amul  Toned Milk",
        category: "Dairy Product",
        company: "Amul",
        price: 120,
        quantity:"500 ml",
        selflife: "1 days",
        display: "mainpage",
        keyfeature:"Wholesome taste Healthy and nutritious milkRich in calcium",
        description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
        mainimage: "images/amulmilk.webp",
        subimage: ["images/amulmilk.webp", "images/milk2.webp", "images/mainingredient.webp","images/mainingredient1.webp"],
    },
    {
        id: "a2",
        name: "Mother Dairy  Curd",
        category: "Dairy Product",
          company: "Mother Dairy",
        price: 70,
        display: "mainpage",
        keyfeature:"Wholesome taste Healthy and nutritious milkRich in calcium",
         description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
        quantity:"250 g",
        selflife: "1 days",
        description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
        mainimage: "images/curd.webp",
        subimage: [ "images/curd.webp","images/curd1.webp", "images/curd2.webp", "images/curd3.webp"],
    },
    {
        id: "a3",
        name: "Amul Salted Butter",
        category: "Dairy Product",
          company: "Amul",
        price: "500 g",
        display: "mainpage",
        keyfeature:"Wholesome taste Healthy and nutritious milkRich in calcium",
        quantity:"500 g",
        selflife: "1 month",
        description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
        mainimage: "images/butter.webp",
        subimage: ["images/butter.webp", "images/butter1.webp", "images/butter2.webp","images/butter3.webp"],
    },
    {
        id: "a4",
        name: " Sandwich Bread",
        category: "Dairy Product",
          company: "Mother Dairy",
        price: 45,
        quantity:"100 g",
        display: "mainpage",
        keyfeature:"Wholesome taste Healthy and nutritious milkRich in calcium",
        selflife: "5 days",
        description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
        mainimage: "images/bread.webp",
        subimage: ["images/bread.webp", "images/bread1.webp", "images/bread2.webp","images/bread3.webp"],
    },
    {
        id: "a5",
        name: "Amul Cheese Cubes",
          company: "Amul",
          display: "mainpage",
        category: "Dairy Product",
        description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
        price: 120,
        quantity:"250 g",
        keyfeature:"Wholesome taste Healthy and nutritious milkRich in calcium",
        selflife: "1 days",
        mainimage: "images/cheese.webp",
        subimage: ["images/cheese.webp", "images/cheese1.webp", "images/cheese2.webp","images/cheese3.webp"],
    },
    {
        id: "a6",
        name: "Health Pizza Base",
          company: "Amul",
        category: "Dairy Product",
        price: 85,
        quantity:"100 g",
        display: "mainpage",
        selflife: "1 days",
        description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
       
        keyfeature:"Wholesome taste Healthy and nutritious milkRich in calcium",
        mainimage: "images/pizza.webp",
        subimage: [ "images/pizza.webp",  "images/pizza1.webp",  "images/pizza2.webp", "images/pizza3.webp"],
    },
    {
        id: "a7",
        name: "Rabri by Amul",   
        category: "Dairy Product",
          company: "Amul",
        price: 50,
        quantity:"50 g",
        display: "mainpage",
        description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
        keyfeature:"Wholesome taste Healthy and nutritious milkRich in calcium",
        selflife: "1 days",
        mainimage: "images/rabdi.webp",
        subimage: [ "images/rabdi.webp",  "images/rabdi1.webp",  "images/rabd2.webp", "images/rabdi3.webp"],
    },
    {
        id: "a8",
        name: "paneer",
        category: "Dairy Product",
          company: "Amul",
        price: 50,
        quantity:"50 g",
        display: "listingpage",
        selflife: "1 days",
        mainimage: "images/paneer.webp",
        subimage: [ "images/paneer.webp",  "images/paneer1.webp",  "images/paneer2.webp", "images/paneer3.webp"],
    },
    {
      id: "a9",
      name: "paneer tika",
      category: "Dairy Product",
        company: "Amul",
      price: 50,
      quantity:"50 g",
      display: "listingpage",
      selflife: "1 days",
      mainimage: "images/paneertika.webp",
      subimage: [ "images/paneertika.webp",  "images/paneertika1.webp",  "images/paneertika2.webp", "images/paneertika3.webp"],
  },
  {
    id: "a10",
    name: "Cheese Slices",
    category: "Dairy Product",
      company: "Amul",
    price: 50,
    quantity:"50 g",
    display: "listingpage",
    selflife: "1 days",
    mainimage: "images/cheeseslice.webp",
    subimage: [ "images/cheeseslice.webp",  "images/cheeseslice1.webp",  "images/cheeseslice2.webp", "images/cheeseslice3.webp"],
},
{
  id: "a11",
  name: "Amul Ghee",
  category: "Dairy Product",
    company: "A",
  price: 50,
  quantity:"50 g",
  display: "listingpage",
  selflife: "1 days",
  mainimage:"images/amulghee.webp",
  subimage: ["images/amulghee.webp", "images/amulghee1.webp", "images/amulghee2.webp", "images/amulghee3.webp"],
},
{
  id: "a12",
  name: "Britania Cheese",
  category: "Dairy Product",
    company: "Britania",
  price: 50,
  quantity:"50 g",
  display: "listingpage",
  selflife: "1 days",
  mainimage:"images/britaniacheese.webp",
  subimage: ["images/britaniacheese.webp", "images/britaniacheese1.webp", "images/britaniacheese2.webp", "images/britaniacheese3.webp"],
},
{
  id: "a13",
  name: "Amul Cheese",
  category: "Dairy Product",
    company: "Amul",
  price: 50,
  quantity:"50 g",
  display: "listingpage",
  selflife: "1 days",
  mainimage:"images/dicedcheese.webp",
  subimage: [ "images/dicedcheese.webp",  "images/dicedcheese1.webp",  "images/dicedcheese2.webp", "images/dicedcheese3.webp"],
},
{
  id: "a14",
  name: "Greek Yogurt",
  category: "Dairy Product",
    company: "Delecious",
  price: 50,
  quantity:"50 g",
  display: "listingpage",
  selflife: "1 days",
  mainimage:"images/greekyogurtlist.webp",
  subimage: ["images/greekyogurtlist.webp", "images/greekyogurtlist1.webp", "images/greekyogurtlist2.webp", "images/greekyogurtlist3.webp"],
},
{
  id: "a15",
  name: "Fruit Yogurt",
  category: "Dairy Product",
    company: "Delecious",
  price: 50,
  quantity:"50 g",
  display: "listingpage",
  selflife: "1 days",
  mainimage:"images/fruityogurt.webp",
  subimage: ["images/fruityogurt.webp", "images/fruityogurt1.webp", "images/fruityogurt2.webp", "images/fruityogurt3.webp"],
},
  {
    id:"b1",
    name: "Bourbon Creme Biscuit ",
    company: "Britania",
    category: "Snacks",
    price: 520,
    quantity:"100 g",
    display: "mainpage",
    selflife:"12 months",
     description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    keyfeature:"Goodness of Wheat: Healthy digestive biscuit with rich blend of wheat (atta) flour and wheat branHi Fibre: Contains high dietary fibre that aids digestive health. A healthy snacking option for anytime.Zero Trans Fat: Contains no trans-fat.",
   ingredient:"WHEAT FLOUR (ATTA) (63%), REFINED PALM OIL, SUGAR, WHEAT |BRAN (4.7%), LIQUID GLUCOSE, MILK SOLIDS, MALTODEXTRIN,RAISING AGENTS (500i) & 503(iil], I0DISED SALT, EMULSIFIERS[322(i), 471 & 472¢], NATURAL, NATURE IDENTICAL & ARTIFICIAL(VANILLA) FLAVOURING SUBSTANCES, MALT EXTRACT ANDDOUGH CONDITIONER (223).(Numbers in brackets as per InternationalNumbering System) |CONTAINS WHEAT, MILK, SOYA, BARLEY AND SULPHITE.",
    mainimage: "images/biscuit.webp",
    subimage: ["images/biscuit.webp", "images/biscuit1.webp", "images/biscuit2.webp","images/biscuit3.webp"],
  },
  {
    id:"b2",
    name: " Oreo Vanilla Biscuit ",
    category: "Snacks",
      company: "  Oreo",
    price: 40,
    display: "mainpage",
    quantity:"50 g",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    selflife:"12 months",
    keyfeature:"Goodness of Wheat: Healthy digestive biscuit with rich blend of wheat (atta) flour and wheat branHi Fibre: Contains high dietary fibre that aids digestive health. A healthy snacking option for anytime.Zero Trans Fat: Contains no trans-fat.",
    ingredient:"WHEAT FLOUR (ATTA) (63%), REFINED PALM OIL, SUGAR, WHEAT |BRAN (4.7%), LIQUID GLUCOSE, MILK SOLIDS, MALTODEXTRIN,RAISING AGENTS (500i) & 503(iil], I0DISED SALT, EMULSIFIERS[322(i), 471 & 472¢], NATURAL, NATURE IDENTICAL & ARTIFICIAL(VANILLA) FLAVOURING SUBSTANCES, MALT EXTRACT ANDDOUGH CONDITIONER (223).(Numbers in brackets as per InternationalNumbering System) |CONTAINS WHEAT, MILK, SOYA, BARLEY AND SULPHITE.",
    mainimage: "images/oreo.webp",
    subimage: ["images/oreo.webp", "images/oreo1.webp", "images/oreo2.webp","images/oreo3.webp"],
  },
  {
    id:"b3",
    name: "Lotte Choco Pie",
    category: "Snacks",
      company: "Lotte",
    price: 200,
    quantity:"400 g",
    display: "mainpage",
    selflife:"12 months",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    keyfeature:"Goodness of Wheat: Healthy digestive biscuit with rich blend of wheat (atta) flour and wheat branHi Fibre: Contains high dietary fibre that aids digestive health. A healthy snacking option for anytime.Zero Trans Fat: Contains no trans-fat.",
    ingredient:"WHEAT FLOUR (ATTA) (63%), REFINED PALM OIL, SUGAR, WHEAT |BRAN (4.7%), LIQUID GLUCOSE, MILK SOLIDS, MALTODEXTRIN,RAISING AGENTS (500i) & 503(iil], I0DISED SALT, EMULSIFIERS[322(i), 471 & 472¢], NATURAL, NATURE IDENTICAL & ARTIFICIAL(VANILLA) FLAVOURING SUBSTANCES, MALT EXTRACT ANDDOUGH CONDITIONER (223).(Numbers in brackets as per InternationalNumbering System) |CONTAINS WHEAT, MILK, SOYA, BARLEY AND SULPHITE.",
    mainimage: "images/loty.webp",
    subimage: ["images/loty.webp", "images/loty1.webp", "images/loty2.webp","images/loty3.webp"],
  },
  {
    id:"b4",
    name: " 50-50 Biscuit",
    category: "Snacks",
      company: " Britania",
    price: 150,
    quantity:"200 g",
    display: "mainpage",
    selflife:"12 months",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    keyfeature:"Goodness of Wheat: Healthy digestive biscuit with rich blend of wheat (atta) flour and wheat branHi Fibre: Contains high dietary fibre that aids digestive health. A healthy snacking option for anytime.Zero Trans Fat: Contains no trans-fat.",
    ingredient:"WHEAT FLOUR (ATTA) (63%), REFINED PALM OIL, SUGAR, WHEAT |BRAN (4.7%), LIQUID GLUCOSE, MILK SOLIDS, MALTODEXTRIN,RAISING AGENTS (500i) & 503(iil], I0DISED SALT, EMULSIFIERS[322(i), 471 & 472¢], NATURAL, NATURE IDENTICAL & ARTIFICIAL(VANILLA) FLAVOURING SUBSTANCES, MALT EXTRACT ANDDOUGH CONDITIONER (223).(Numbers in brackets as per InternationalNumbering System) |CONTAINS WHEAT, MILK, SOYA, BARLEY AND SULPHITE.",
    mainimage: "images/5050.webp",
    subimage: ["images/5050.webp", "images/50501.webp", "images/50502.webp","images/50503.webp"],
  },
  {
    id:"b5",
    name: "Saffola Masala Oats",
      company: "soffola",
    category: "Snacks",
    price: 50,
    quantity:"50 g",
    display: "mainpage",
    selflife:"12 months",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    keyfeature:"Goodness of Wheat: Healthy digestive biscuit with rich blend of wheat (atta) flour and wheat branHi Fibre: Contains high dietary fibre that aids digestive health. A healthy snacking option for anytime.Zero Trans Fat: Contains no trans-fat.",
    ingredient:"WHEAT FLOUR (ATTA) (63%), REFINED PALM OIL, SUGAR, WHEAT |BRAN (4.7%), LIQUID GLUCOSE, MILK SOLIDS, MALTODEXTRIN,RAISING AGENTS (500i) & 503(iil], I0DISED SALT, EMULSIFIERS[322(i), 471 & 472¢], NATURAL, NATURE IDENTICAL & ARTIFICIAL(VANILLA) FLAVOURING SUBSTANCES, MALT EXTRACT ANDDOUGH CONDITIONER (223).(Numbers in brackets as per InternationalNumbering System) |CONTAINS WHEAT, MILK, SOYA, BARLEY AND SULPHITE.",
    mainimage: "images/oats.webp",
    subimage: ["images/oats.webp", "images/oats1.webp", "images/oats2.webp","images/oats3.webp"],
  },
  {
    id:"b6",
    name: "Dark Fantasy Biscuit ",
    category: "Snacks",
      company: "  Britania",
    price: 80,
    quantity:"450 g",
    display: "mainpage",
    selflife:"12 months",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    keyfeature:"Goodness of Wheat: Healthy digestive biscuit with rich blend of wheat (atta) flour and wheat branHi Fibre: Contains high dietary fibre that aids digestive health. A healthy snacking option for anytime.Zero Trans Fat: Contains no trans-fat.",
    ingredient:"WHEAT FLOUR (ATTA) (63%), REFINED PALM OIL, SUGAR, WHEAT |BRAN (4.7%), LIQUID GLUCOSE, MILK SOLIDS, MALTODEXTRIN,RAISING AGENTS (500i) & 503(iil], I0DISED SALT, EMULSIFIERS[322(i), 471 & 472¢], NATURAL, NATURE IDENTICAL & ARTIFICIAL(VANILLA) FLAVOURING SUBSTANCES, MALT EXTRACT ANDDOUGH CONDITIONER (223).(Numbers in brackets as per InternationalNumbering System) |CONTAINS WHEAT, MILK, SOYA, BARLEY AND SULPHITE.",
    mainimage: "images/darkfantasy.webp",
    subimage: ["images/darkfantasy.webp", "images/darkfantasy1.webp", "images/darkfantasy2.webp","images/darkfantasy3.webp"],
  },
  {
    id:"b7",
    name: " GoodDay Cashew Biscuit",
    category: "Snacks",
      company: "Britania",
    price: 110,
    quantity:"100 g",
    display: "mainpage",
    selflife:"12 months",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    keyfeature:"Goodness of Wheat: Healthy digestive biscuit with rich blend of wheat (atta) flour and wheat branHi Fibre: Contains high dietary fibre that aids digestive health. A healthy snacking option for anytime.Zero Trans Fat: Contains no trans-fat.",
    ingredient:"WHEAT FLOUR (ATTA) (63%), REFINED PALM OIL, SUGAR, WHEAT |BRAN (4.7%), LIQUID GLUCOSE, MILK SOLIDS, MALTODEXTRIN,RAISING AGENTS (500i) & 503(iil], I0DISED SALT, EMULSIFIERS[322(i), 471 & 472¢], NATURAL, NATURE IDENTICAL & ARTIFICIAL(VANILLA) FLAVOURING SUBSTANCES, MALT EXTRACT ANDDOUGH CONDITIONER (223).(Numbers in brackets as per InternationalNumbering System) |CONTAINS WHEAT, MILK, SOYA, BARLEY AND SULPHITE.",
    mainimage: "images/goodday.webp",
    subimage: ["images/goodday.webp", "images/goodday1.webp", "images/goodday2.webp","images/goodday3.webp"],
  },
  {
    id:"c1",
    name: "Lay's Chilli  ",
    category: "Chips",
      company: "Lay's",
    price: 40,
    quantity:"25 g",
    flavour:"Chilli",
    display: "mainpage",
    selflife:"12 months",
    keyfeature:"Wholesome taste Healthy and nutritious milkRich in calcium",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    ingredient:"Lay’s West Indies Hot 'n' Sweet Chilli flavour will ignite your tastebuds.Made from the highest quality, farm-grown potatoes.Lay’s West Indies Hot 'n' Sweet Chilli is a 100% vegetarian snack.A versatile snack that can be enjoyed in any setting.Lay’s is always on the lookout for the best flavours, cuts, and innovations that are guaranteed to bring a smile to your face.",
    mainimage: "images/lays.webp",
    subimage: ["images/lays.webp", "images/lays1.webp", "images/lays2.webp","images/lays3.webp"],
  },
  {
    id:"c2",
    name: "Doritos Cheese Nachos",
    category: "Chips",
      company: "Doritos",
    price: 40,
    quantity:"40 g",
    display: "mainpage",
    selflife:"12 months",
    keyfeature:"Wholesome taste Healthy and nutritious milkRich in calcium",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    ingredient:"Lay’s West Indies Hot 'n' Sweet Chilli flavour will ignite your tastebuds.Made from the highest quality, farm-grown potatoes.Lay’s West Indies Hot 'n' Sweet Chilli is a 100% vegetarian snack.A versatile snack that can be enjoyed in any setting.Lay’s is always on the lookout for the best flavours, cuts, and innovations that are guaranteed to bring a smile to your face.",
    mainimage: "images/doritos.webp",
    subimage: ["images/doritos.webp", "images/doritos1.webp", "images/doritos2.webp","images/doritos3.webp"],
  },
  {
    id:"c3",
    name: "Pringles Sour  Chips",
    category: "Chips",
      company: "Pringles",
    price: 35,
    quantity:"100 g",
    display: "mainpage",
    selflife:"12 months",
    keyfeature:"Wholesome taste Healthy and nutritious milkRich in calcium",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    ingredient:"Lay’s West Indies Hot 'n' Sweet Chilli flavour will ignite your tastebuds.Made from the highest quality, farm-grown potatoes.Lay’s West Indies Hot 'n' Sweet Chilli is a 100% vegetarian snack.A versatile snack that can be enjoyed in any setting.Lay’s is always on the lookout for the best flavours, cuts, and innovations that are guaranteed to bring a smile to your face.",
    mainimage: "images/prin.webp",
    subimage: ["images/prin.webp", "images/prin1.webp", "images/prin2.webp","images/prin3.webp"],
  },
  {
    id:"c4",
    name: "Lay's Limon  Chips",
    category: "Chips",
      company: "Lay's",
    price: 20,
    quantity:"28 g",
    display: "mainpage",
    selflife:"12 months",
    keyfeature:"Wholesome taste Healthy and nutritious milkRich in calcium",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    ingredient:"Lay’s West Indies Hot 'n' Sweet Chilli flavour will ignite your tastebuds.Made from the highest quality, farm-grown potatoes.Lay’s West Indies Hot 'n' Sweet Chilli is a 100% vegetarian snack.A versatile snack that can be enjoyed in any setting.Lay’s is always on the lookout for the best flavours, cuts, and innovations that are guaranteed to bring a smile to your face.",
    mainimage: "images/layslemon.webp",
    subimage: ["images/layslemon.webp", "images/layslemon1.webp", "images/layslemon2.webp","images/layslemon3.webp"],
  },
  {
    id:"c5",
    name: "Bingo Mad Angles",
    category: "Chips",
      company: "Bingo",
    price: 50,
    quantity:"50 g",
    display: "mainpage",
    selflife:"12 months",
    keyfeature:"Wholesome taste Healthy and nutritious milkRich in calcium",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    ingredient:"Lay’s West Indies Hot 'n' Sweet Chilli flavour will ignite your tastebuds.Made from the highest quality, farm-grown potatoes.Lay’s West Indies Hot 'n' Sweet Chilli is a 100% vegetarian snack.A versatile snack that can be enjoyed in any setting.Lay’s is always on the lookout for the best flavours, cuts, and innovations that are guaranteed to bring a smile to your face.",
    mainimage: "images/bingo.webp",
    subimage: ["images/bingo.webp", "images/bingo1.webp", "images/bingo2.webp","images/bingo3.webp"],
  },
  {
    id:"c6",
    name: "Beyond Banana Chips",
    category: "Chips",
      company: "Beyond Chips",
    price: 30,
    quantity:"100 g",
    display: "mainpage",
    selflife:"12 months",
    keyfeature:"Wholesome taste Healthy and nutritious milkRich in calcium",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    ingredient:"Lay’s West Indies Hot 'n' Sweet Chilli flavour will ignite your tastebuds.Made from the highest quality, farm-grown potatoes.Lay’s West Indies Hot 'n' Sweet Chilli is a 100% vegetarian snack.A versatile snack that can be enjoyed in any setting.Lay’s is always on the lookout for the best flavours, cuts, and innovations that are guaranteed to bring a smile to your face.",
    mainimage: "images/bananachips.webp",
    subimage: ["images/bananachips.webp", "images/bananachips1.webp", "images/bananachips2.webp","images/bananachips3.webp"],
  },
  {
    id:"c7",
    name: "Beyond Snack Chips",
    category: "Chips",
      company: "Beyond Chips",
    price: 10,
    quantity:"70 g",
    display: "mainpage",
    selflife:"12 months",
    keyfeature:"Wholesome taste Healthy and nutritious milkRich in calcium",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    ingredient:"Lay’s West Indies Hot 'n' Sweet Chilli flavour will ignite your tastebuds.Made from the highest quality, farm-grown potatoes.Lay’s West Indies Hot 'n' Sweet Chilli is a 100% vegetarian snack.A versatile snack that can be enjoyed in any setting.Lay’s is always on the lookout for the best flavours, cuts, and innovations that are guaranteed to bring a smile to your face.",
   description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    mainimage: "images/newchips.webp",
    subimage: ["images/newchips.webp", "images/newchips1.webp", "images/newchips2.webp","images/newchips3.webp"],
  },
{
    id:"d1" ,
    name: " Tata Tea Gold",
    category: "Tea",
      company: "Tata Tea",
    
    price: 200,
    quantity:"200 g",
    display: "mainpage",
    selflife:"12 months",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    ingredient:"Black Tea",
    mainimage: "images/goldtea.webp",
    subimage: ["images/goldtea.webp", "images/goldtea1.webp", "images/goldtea2.webp","images/goldtea3.webp"],
},
{
    id:"d2" ,
    name: "Tata Agni  Tea",
    category: "Tea",
      company: "Tata Tea",
    price: 50,
    quantity:"100 g",
    display: "mainpage",
    selflife:"12 months",
    ingredient:"Black Tea",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    mainimage: "images/aginitea.webp",
    subimage: ["images/aginitea.webp", "images/aginitea1.webp", "images/aginitea2.webp","images/aginitea3.webp"],
},
{
    id:"d3" ,
    name: "Tata Grand Coffee",
    category: "Tea",
      company: "Tata Tea",
    price: 200,
    quantity:"400 g",
    display: "mainpage",
    selflife:"12 months",
    ingredient:"Black Tea",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    mainimage: "images/tatacoffe.webp",
    subimage: ["images/tatacoffe.webp", "images/tatacoffe1.webp", "images/tatacoffe12.webp","images/tatacoffe13.webp"],
   
},
{
    id:"d4" ,
    name: "Lipton Green Tea ",
    category: "Tea",
      company: "Lipton",
    price: 250,
    quantity:"500 g",
    display: "mainpage",
    selflife:"12 months",
    ingredient:"Black Tea",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    mainimage: "images/lipton.webp",
    subimage: ["images/lipton.webp", "images/lipton1.webp", "images/lipton2.webp","images/lipton3.webp"],
},
{
    id:"d5" ,
    name: "Tata Premium Tea ",
    category: "Tea",
    price: 150,
      company: "Tata Tea",
    quantity:"250 g",
    selflife:"12 months",
    display: "mainpage",
    ingredient:"Black Tea",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    mainimage: "images/tatatea1.webp",
    subimage: ["images/tatatea1.webp", "images/tatatea1.webp", "images/tatatea2.webp","images/tatatea3.webp"],
},
{
    id:"d6" ,
    name: "Nescafe Coffee Powder ",
    category: "Tea",
    price: 250,
    quantity:"800 g",
      company: "Nescafe",
    selflife:"12 months",
    display: "mainpage",
    ingredient:"Black Tea",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    mainimage: "images/coffe.webp",
    subimage: ["images/coffe.webp", "images/coffe1.webp", "images/coffe2.webp","images/coffe3.webp"],
},
{
    id:"d7" ,
    name: "TataElaichi Tea",
    category: "Tea",
      company: "Tata Tea",
    price: 80,
    quantity:"100 g",
    display: "mainpage",
    selflife:"12 months",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    ingredient:"Black Tea",
    mainimage: "images/elachitea.webp",
    subimage: ["images/elachitea.webp", "images/elachitea1.webp", "images/elachitea2.webp","images/elachitea3.webp"],
},
];
