let products = [
    {
        id: "a1",
        name: "Milk",
        category: "Dairy Product",
        price: 500,
        mainimage: "images/amulmilk.webp",
        subimage: ["images/amulmilk.webp", "images/milk2.webp", "images/mainingredient.webp","images/mainingredient1.webp"],
    },
    {
        id: "a2",
        name: "Curd",
        category: "Dairy Product",
        price: 500,
        mainimage: "images/curd.webp",
        subimage: [ "images/curd.webp","images/curd1.webp", "images/curd2.webp", "images/curd3.webp"],
    },
    {
        id: "a3",
        name: "Butter",
        category: "Dairy Product",
        price: 500,
        mainimage: "images/butter.webp",
        subimage: ["images/butter.webp", "images/butter1.webp", "images/butter2.webp","images/butter3.webp"],
    },
    {
        id: "a4",
        name: "Bread",
        category: "Dairy Product",
        price: 500,
        mainimage: "images/bread.webp",
        subimage: ["images/bread.webp", "images/bread1.webp", "images/bread2.webp","images/bread3.webp"],
    },
    {
        id: "a5",
        name: "Cheese",
        category: "Dairy Product",
        price: 500,
        mainimage: "images/cheese.webp",
        subimage: ["images/cheese.webp", "images/cheese1.webp", "images/cheese2.webp","images/cheese3.webp"],
    },
    {
        id: "a6",
        name: "Pizza",
        category: "Dairy Product",
        price: 500,
        mainimage: "images/pizza.webp",
        subimage: [ "images/pizza.webp",  "images/pizza1.webp",  "images/pizza2.webp", "images/pizza3.webp"],
    },
    {
        id: "a7",
        name: "Rabdi",   
        category: "Dairy Product",
        price: 500,
        mainimage: "images/rabdi.webp",
        subimage: [ "images/rabdi.webp",  "images/rabdi1.webp",  "images/rabd2.webp", "images/rabdi3.webp"],
    },
  {
    id:"b1",
    name: "Biscuits",
    category: "Snacks",
    price: 500,
    mainimage: "images/biscuit.webp",
    subimage: ["images/biscuit.webp", "images/biscuit1.webp", "images/biscuit2.webp","images/biscuit3.webp"],
  },
  {
    id:"b2",
    name: "Biscuits",
    category: "Snacks",
    price: 500,
    mainimage: "images/oreo.webp",
    subimage: ["images/oreo.webp", "images/oreo1.webp", "images/oreo2.webp","images/oreo3.webp"],
  },
  {
    id:"b3",
    name: "Biscuits",
    category: "Snacks",
    price: 500,
    mainimage: "images/loty.webp",
    subimage: ["images/loty.webp", "images/loty1.webp", "images/loty2.webp","images/loty3.webp"],
  },
  {
    id:"b4",
    name: "Biscuits",
    category: "Snacks",
    price: 500,
    mainimage: "images/5050.webp",
    subimage: ["images/5050.webp", "images/50501.webp", "images/50502.webp","images/50503.webp"],
  },
  {
    id:"b5",
    name: "Biscuits",
    category: "Snacks",
    price: 500,
    mainimage: "images/oats.webp",
    subimage: ["images/oats.webp", "images/oats1.webp", "images/oats2.webp","images/oats3.webp"],
  },
  {
    id:"b6",
    name: "Biscuits",
    category: "Snacks",
    price: 500,
    mainimage: "images/darkfantasy.webp",
    subimage: ["images/darkfantasy.webp", "images/darkfantasy1.webp", "images/darkfantasy2.webp","images/darkfantasy3.webp"],
  },
  {
    id:"b7",
    name: "Biscuits",
    category: "Snacks",
    price: 500,
    mainimage: "images/goodday.webp",
    subimage: ["images/goodday.webp", "images/goodday1.webp", "images/goodday2.webp","images/goodday3.webp"],
  },
  {
    id:"c1",
    name: "Chips",
    category: "Chips",
    price: 500,
    mainimage: "images/lays.webp",
    subimage: ["images/lays.webp", "images/lays1.webp", "images/lays2.webp","images/lays3.webp"],
  },
  {
    id:"c2",
    name: "Chips",
    category: "Chips",
    price: 500,
    mainimage: "images/doritos.webp",
    subimage: ["images/doritos.webp", "images/doritos1.webp", "images/doritos2.webp","images/doritos3.webp"],
  },
  {
    id:"c3",
    name: "Chips",
    category: "Chips",
    price: 500,
    mainimage: "images/prin.webp",
    subimage: ["images/prin.webp", "images/prin1.webp", "images/prin2.webp","images/prin3.webp"],
  },
  {
    id:"c4",
    name: "Chips",
    category: "Chips",
    price: 500,
    mainimage: "images/layslemon.webp",
    subimage: ["images/layslemon.webp", "images/layslemon1.webp", "images/layslemon2.webp","images/layslemon3.webp"],
  },
  {
    id:"c5",
    name: "Chips",
    category: "Chips",
    price: 500,
    mainimage: "images/bingo.webp",
    subimage: ["images/bingo.webp", "images/bingo1.webp", "images/bingo2.webp","images/bingo3.webp"],
  },
  {
    id:"c6",
    name: "Chips",
    category: "Chips",
    price: 500,
    mainimage: "images/bananachips.webp",
    subimage: ["images/bananachips.webp", "images/bananachips1.webp", "images/bananachips2.webp","images/bananachips3.webp"],
  },
  {
    id:"c7",
    name: "Chips",
    category: "Chips",
    price: 500,
    mainimage: "images/newchips.webp",
    subimage: ["images/newchips.webp", "images/newchips1.webp", "images/newchips2.webp","images/newchips3.webp"],
  },
{
    id:"d1" ,
    name: " Tea",
    category: "Tea",
    price: 500,
    mainimage: "images/goldtea.webp",
    subimage: ["images/goldtea.webp", "images/goldtea1.webp", "images/goldtea2.webp","images/goldtea3.webp"],
},
{
    id:"d2" ,
    name: " Tea",
    category: "Tea",
    price: 500,
    mainimage: "images/aginitea.webp",
    subimage: ["images/aginitea.webp", "images/aginitea1.webp", "images/aginitea2.webp","images/aginitea3.webp"],
},
{
    id:"d3" ,
    name: " Tea",
    category: "Tea",
    price: 500,
    mainimage: "images/tatacoffe.webp",
    subimage: ["images/tatacoffe.webp", "images/tatacoffe1.webp", "images/tatacoffe12.webp","images/tatacoffe3.webp"],
   
},
{
    id:"d4" ,
    name: " Tea",
    category: "Tea",
    price: 500,
    mainimage: "images/lipton.webp",
    subimage: ["images/lipton.webp", "images/lipton1.webp", "images/lipton2.webp","images/lipton3.webp"],
},
{
    id:"d5" ,
    name: " Tea",
    category: "Tea",
    price: 500,
    mainimage: "images/tatatea1.webp",
    subimage: ["images/tatatea1.webp", "images/tatatea1.webp", "images/tatatea2.webp","images/tatatea3.webp"],
},
{
    id:"d6" ,
    name: " Tea",
    category: "Tea",
    price: 500,
    mainimage: "images/coffe.webp",
    subimage: ["images/coffe.webp", "images/coffe1.webp", "images/coffe2.webp","images/coffe3.webp"],
},
{
    id:"d7" ,
    name: " Tea",
    category: "Tea",
    price: 500,
    mainimage: "images/elachitea.webp",
    subimage: ["images/elachitea.webp", "images/elachitea1.webp", "images/elachitea2.webp","images/elachitea3.webp"],
},
];
