let products = [
    {
        id: "a1",
        name: "Amul  Toned Milk",
        category: "DairyProduct",
        company: "Amul",
        price: 120,
        quantity:"500 ml",
        selflife: "1 days",
        display: "mainpage",
        keyfeature:"Wholesome taste Healthy and nutritious milkRich in calcium",
        description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
        mainimage: "images/amulmilk.webp",
        subimage: ["images/amulmilk.webp", "images/milk2.webp", "images/mainingredient.webp","images/mainingredient1.webp"],
    },
    {
        id: "a2",
        name: "Mother Dairy  Curd",
        category: "DairyProduct",
          company: "Mother Dairy",
        price: 70,
        display: "mainpage",
        keyfeature:"Wholesome taste Healthy and nutritious milkRich in calcium",
         description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
        quantity:"250 g",
        selflife: "1 days",
        description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
        mainimage: "images/curd.webp",
        subimage: [ "images/curd.webp","images/curd1.webp", "images/curd2.webp", "images/curd3.webp"],
    },
    {
        id: "a3",
        name: "Amul Salted Butter",
        category: "DairyProduct",
          company: "Amul",
        price: "500 g",
        display: "mainpage",
        keyfeature:"Wholesome taste Healthy and nutritious milkRich in calcium",
        quantity:"500 g",
        selflife: "1 month",
        description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
        mainimage: "images/butter.webp",
        subimage: ["images/butter.webp", "images/butter1.webp", "images/butter2.webp","images/butter3.webp"],
    },
    {
        id: "a4",
        name: " Sandwich Bread",
        category: "DairyProduct",
          company: "Mother Dairy",
        price: 45,
        quantity:"100 g",
        display: "mainpage",
        keyfeature:"Wholesome taste Healthy and nutritious milkRich in calcium",
        selflife: "5 days",
        description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
        mainimage: "images/bread.webp",
        subimage: ["images/bread.webp", "images/bread1.webp", "images/bread2.webp","images/bread3.webp"],
    },
    {
        id: "a5",
        name: "Amul Cheese Cubes",
          company: "Amul",
          display: "mainpage",
        category: "DairyProduct",
        description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
        price: 120,
        quantity:"250 g",
        keyfeature:"Wholesome taste Healthy and nutritious milkRich in calcium",
        selflife: "1 days",
        mainimage: "images/cheese.webp",
        subimage: ["images/cheese.webp", "images/cheese1.webp", "images/cheese2.webp","images/cheese3.webp"],
    },
    {
        id: "a6",
        name: "Health Pizza Base",
          company: "Amul",
        category: "DairyProduct",
        price: 85,
        quantity:"100 g",
        display: "mainpage",
        selflife: "1 days",
        description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
       
        keyfeature:"Wholesome taste Healthy and nutritious milkRich in calcium",
        mainimage: "images/pizza.webp",
        subimage: [ "images/pizza.webp",  "images/pizza1.webp",  "images/pizza2.webp", "images/pizza3.webp"],
    },
    {
        id: "a7",
        name: "Rabri by Amul",   
        category: "DairyProduct",
          company: "Amul",
        price: 50,
        quantity:"50 g",
        display: "mainpage",
        description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
        keyfeature:"Wholesome taste Healthy and nutritious milkRich in calcium",
        selflife: "1 days",
        mainimage: "images/rabdi.webp",
        subimage: [ "images/rabdi.webp",  "images/rabdi1.webp",  "images/rabd2.webp", "images/rabdi3.webp"],
    },
    {
        id: "a8",
        name: "paneer",
        category: "DairyProduct",
          company: "Amul",
        price: 50,
        quantity:"50 g",
        display: "listingpage",
        selflife: "1 days",
        mainimage: "images/paneer.webp",
        subimage: [ "images/paneer.webp",  "images/paneer1.webp",  "images/paneer2.webp", "images/paneer3.webp"],
    },
    {
      id: "a9",
      name: "paneer tika",
      category: "DairyProduct",
        company: "Amul",
      price: 50,
      quantity:"50 g",
      display: "listingpage",
      selflife: "1 days",
      mainimage: "images/paneertika.webp",
      subimage: [ "images/paneertika.webp",  "images/paneertika1.webp",  "images/paneertika2.webp", "images/paneertika3.webp"],
  },
  {
    id: "a10",
    name: "Cheese Slices",
    category: "DairyProduct",
      company: "Amul",
    price: 50,
    quantity:"50 g",
    display: "listingpage",
    selflife: "1 days",
    mainimage: "images/cheeseslice.webp",
    subimage: [ "images/cheeseslice.webp",  "images/cheeseslice1.webp",  "images/cheeseslice2.webp", "images/cheeseslice3.webp"],
},
{
  id: "a11",
  name: "Amul Ghee",
  category: "DairyProduct",
    company: "A",
  price: 50,
  quantity:"50 g",
  display: "listingpage",
  selflife: "1 days",
  mainimage:"images/amulghee.webp",
  subimage: ["images/amulghee.webp", "images/amulghee1.webp", "images/amulghee2.webp", "images/amulghee3.webp"],
},
{
  id: "a12",
  name: "Britania Cheese",
  category: "DairyProduct",
    company: "Britania",
  price: 50,
  quantity:"50 g",
  display: "listingpage",
  selflife: "1 days",
  mainimage:"images/britaniacheese.webp",
  subimage: ["images/britaniacheese.webp", "images/britaniacheese1.webp", "images/britaniacheese2.webp", "images/britaniacheese3.webp"],
},
{
  id: "a13",
  name: "Amul Cheese",
  category: "DairyProduct",
    company: "Amul",
  price: 50,
  quantity:"50 g",
  display: "listingpage",
  selflife: "1 days",
  mainimage:"images/dicedcheese.webp",
  subimage: [ "images/dicedcheese.webp",  "images/dicedcheese1.webp",  "images/dicedcheese2.webp", "images/dicedcheese3.webp"],
},
{
  id: "a14",
  name: "Greek Yogurt",
  category: "DairyProduct",
    company: "Delecious",
  price: 50,
  quantity:"50 g",
  display: "listingpage",
  selflife: "1 days",
  mainimage:"images/greekyogurtlist.webp",
  subimage: ["images/greekyogurtlist.webp", "images/greekyogurtlist1.webp", "images/greekyogurtlist2.webp", "images/greekyogurtlist3.webp"],
},
{
  id: "a15",
  name: "Fruit Yogurt",
  category: "DairyProduct",
    company: "Delecious",
  price: 50,
  quantity:"50 g",
  display: "listingpage",
  selflife: "1 days",
  mainimage:"images/fruityogurt.webp",
  subimage: ["images/fruityogurt.webp", "images/fruityogurt1.webp", "images/fruityogurt2.webp", "images/fruityogurt3.webp"],
},
  {
    id:"b1",
    name: "Bourbon Creme Biscuit ",
    company: "Britania",
    category: "Snacks",
    price: 520,
    quantity:"100 g",
    display: "mainpage",
    selflife:"12 months",
     description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    keyfeature:"Goodness of Wheat: Healthy digestive biscuit with rich blend of wheat (atta) flour and wheat branHi Fibre: Contains high dietary fibre that aids digestive health. A healthy snacking option for anytime.Zero Trans Fat: Contains no trans-fat.",
   ingredient:"WHEAT FLOUR (ATTA) (63%), REFINED PALM OIL, SUGAR, WHEAT |BRAN (4.7%), LIQUID GLUCOSE, MILK SOLIDS, MALTODEXTRIN,RAISING AGENTS (500i) & 503(iil], I0DISED SALT, EMULSIFIERS[322(i), 471 & 472¢], NATURAL, NATURE IDENTICAL & ARTIFICIAL(VANILLA) FLAVOURING SUBSTANCES, MALT EXTRACT ANDDOUGH CONDITIONER (223).(Numbers in brackets as per InternationalNumbering System) |CONTAINS WHEAT, MILK, SOYA, BARLEY AND SULPHITE.",
    mainimage: "images/biscuit.webp",
    subimage: ["images/biscuit.webp", "images/biscuit1.webp", "images/biscuit2.webp","images/biscuit3.webp"],
  },
  {
    id:"b2",
    name: " Oreo Vanilla Biscuit ",
    category: "Snacks",
      company: "  Oreo",
    price: 40,
    display: "mainpage",
    quantity:"50 g",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    selflife:"12 months",
    keyfeature:"Goodness of Wheat: Healthy digestive biscuit with rich blend of wheat (atta) flour and wheat branHi Fibre: Contains high dietary fibre that aids digestive health. A healthy snacking option for anytime.Zero Trans Fat: Contains no trans-fat.",
    ingredient:"WHEAT FLOUR (ATTA) (63%), REFINED PALM OIL, SUGAR, WHEAT |BRAN (4.7%), LIQUID GLUCOSE, MILK SOLIDS, MALTODEXTRIN,RAISING AGENTS (500i) & 503(iil], I0DISED SALT, EMULSIFIERS[322(i), 471 & 472¢], NATURAL, NATURE IDENTICAL & ARTIFICIAL(VANILLA) FLAVOURING SUBSTANCES, MALT EXTRACT ANDDOUGH CONDITIONER (223).(Numbers in brackets as per InternationalNumbering System) |CONTAINS WHEAT, MILK, SOYA, BARLEY AND SULPHITE.",
    mainimage: "images/oreo.webp",
    subimage: ["images/oreo.webp", "images/oreo1.webp", "images/oreo2.webp","images/oreo3.webp"],
  },
  {
    id:"b3",
    name: "Lotte Choco Pie",
    category: "Snacks",
      company: "Lotte",
    price: 200,
    quantity:"400 g",
    display: "mainpage",
    selflife:"12 months",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    keyfeature:"Goodness of Wheat: Healthy digestive biscuit with rich blend of wheat (atta) flour and wheat branHi Fibre: Contains high dietary fibre that aids digestive health. A healthy snacking option for anytime.Zero Trans Fat: Contains no trans-fat.",
    ingredient:"WHEAT FLOUR (ATTA) (63%), REFINED PALM OIL, SUGAR, WHEAT |BRAN (4.7%), LIQUID GLUCOSE, MILK SOLIDS, MALTODEXTRIN,RAISING AGENTS (500i) & 503(iil], I0DISED SALT, EMULSIFIERS[322(i), 471 & 472¢], NATURAL, NATURE IDENTICAL & ARTIFICIAL(VANILLA) FLAVOURING SUBSTANCES, MALT EXTRACT ANDDOUGH CONDITIONER (223).(Numbers in brackets as per InternationalNumbering System) |CONTAINS WHEAT, MILK, SOYA, BARLEY AND SULPHITE.",
    mainimage: "images/loty.webp",
    subimage: ["images/loty.webp", "images/loty1.webp", "images/loty2.webp","images/loty3.webp"],
  },
  {
    id:"b4",
    name: " 50-50 Biscuit",
    category: "Snacks",
      company: " Britania",
    price: 150,
    quantity:"200 g",
    display: "mainpage",
    selflife:"12 months",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    keyfeature:"Goodness of Wheat: Healthy digestive biscuit with rich blend of wheat (atta) flour and wheat branHi Fibre: Contains high dietary fibre that aids digestive health. A healthy snacking option for anytime.Zero Trans Fat: Contains no trans-fat.",
    ingredient:"WHEAT FLOUR (ATTA) (63%), REFINED PALM OIL, SUGAR, WHEAT |BRAN (4.7%), LIQUID GLUCOSE, MILK SOLIDS, MALTODEXTRIN,RAISING AGENTS (500i) & 503(iil], I0DISED SALT, EMULSIFIERS[322(i), 471 & 472¢], NATURAL, NATURE IDENTICAL & ARTIFICIAL(VANILLA) FLAVOURING SUBSTANCES, MALT EXTRACT ANDDOUGH CONDITIONER (223).(Numbers in brackets as per InternationalNumbering System) |CONTAINS WHEAT, MILK, SOYA, BARLEY AND SULPHITE.",
    mainimage: "images/5050.webp",
    subimage: ["images/5050.webp", "images/50501.webp", "images/50502.webp","images/50503.webp"],
  },
  {
    id:"b5",
    name: "Saffola Masala Oats",
      company: "soffola",
    category: "Snacks",
    price: 50,
    quantity:"50 g",
    display: "mainpage",
    selflife:"12 months",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    keyfeature:"Goodness of Wheat: Healthy digestive biscuit with rich blend of wheat (atta) flour and wheat branHi Fibre: Contains high dietary fibre that aids digestive health. A healthy snacking option for anytime.Zero Trans Fat: Contains no trans-fat.",
    ingredient:"WHEAT FLOUR (ATTA) (63%), REFINED PALM OIL, SUGAR, WHEAT |BRAN (4.7%), LIQUID GLUCOSE, MILK SOLIDS, MALTODEXTRIN,RAISING AGENTS (500i) & 503(iil], I0DISED SALT, EMULSIFIERS[322(i), 471 & 472¢], NATURAL, NATURE IDENTICAL & ARTIFICIAL(VANILLA) FLAVOURING SUBSTANCES, MALT EXTRACT ANDDOUGH CONDITIONER (223).(Numbers in brackets as per InternationalNumbering System) |CONTAINS WHEAT, MILK, SOYA, BARLEY AND SULPHITE.",
    mainimage: "images/oats.webp",
    subimage: ["images/oats.webp", "images/oats1.webp", "images/oats2.webp","images/oats3.webp"],
  },
  {
    id:"b6",
    name: "Dark Fantasy Biscuit ",
    category: "Snacks",
      company: "  Britania",
    price: 80,
    quantity:"450 g",
    display: "mainpage",
    selflife:"12 months",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    keyfeature:"Goodness of Wheat: Healthy digestive biscuit with rich blend of wheat (atta) flour and wheat branHi Fibre: Contains high dietary fibre that aids digestive health. A healthy snacking option for anytime.Zero Trans Fat: Contains no trans-fat.",
    ingredient:"WHEAT FLOUR (ATTA) (63%), REFINED PALM OIL, SUGAR, WHEAT |BRAN (4.7%), LIQUID GLUCOSE, MILK SOLIDS, MALTODEXTRIN,RAISING AGENTS (500i) & 503(iil], I0DISED SALT, EMULSIFIERS[322(i), 471 & 472¢], NATURAL, NATURE IDENTICAL & ARTIFICIAL(VANILLA) FLAVOURING SUBSTANCES, MALT EXTRACT ANDDOUGH CONDITIONER (223).(Numbers in brackets as per InternationalNumbering System) |CONTAINS WHEAT, MILK, SOYA, BARLEY AND SULPHITE.",
    mainimage: "images/darkfantasy.webp",
    subimage: ["images/darkfantasy.webp", "images/darkfantasy1.webp", "images/darkfantasy2.webp","images/darkfantasy3.webp"],
  },
  {
    id:"b7",
    name: " GoodDay Cashew Biscuit",
    category: "Snacks",
      company: "Britania",
    price: 110,
    quantity:"100 g",
    display: "mainpage",
    selflife:"12 months",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    keyfeature:"Goodness of Wheat: Healthy digestive biscuit with rich blend of wheat (atta) flour and wheat branHi Fibre: Contains high dietary fibre that aids digestive health. A healthy snacking option for anytime.Zero Trans Fat: Contains no trans-fat.",
    ingredient:"WHEAT FLOUR (ATTA) (63%), REFINED PALM OIL, SUGAR, WHEAT |BRAN (4.7%), LIQUID GLUCOSE, MILK SOLIDS, MALTODEXTRIN,RAISING AGENTS (500i) & 503(iil], I0DISED SALT, EMULSIFIERS[322(i), 471 & 472¢], NATURAL, NATURE IDENTICAL & ARTIFICIAL(VANILLA) FLAVOURING SUBSTANCES, MALT EXTRACT ANDDOUGH CONDITIONER (223).(Numbers in brackets as per InternationalNumbering System) |CONTAINS WHEAT, MILK, SOYA, BARLEY AND SULPHITE.",
    mainimage: "images/goodday.webp",
    subimage: ["images/goodday.webp", "images/goodday1.webp", "images/goodday2.webp","images/goodday3.webp"],
  },
  {
id :"b8",
name:"chocochips ",
category: "Snacks",
company: "Britania",
price: 100,
quantity:"100g",
display: "listingpage",
selflife:"1 year",
description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
keyfeature:"Goodness of Wheat: Healthy digestive biscuit with rich blend of wheat (atta) flour and wheat branHi Fibre: Contains high dietary fibre that aids digestive health. A healthy snacking option for anytime.Zero Trans Fat: Contains no trans-fat.",
ingredient:"WHEAT FLOUR (ATTA) (63%), REFINED PALM OIL, SUGAR, WHEAT |BRAN (4.7%), LIQUID GLUCOSE, MILK SOLIDS, MALTODEXTRIN,RAISING AGENTS (500i) & 503(iil], I0DISED SALT, EMULSIFIERS[322(i), 471 & 472¢], NATURAL, NATURE IDENTICAL & ARTIFICIAL(VANILLA) FLAVOURING SUBSTANCES, MALT EXTRACT ANDDOUGH CONDITIONER (223).(Numbers in brackets as per InternationalNumbering System) |CONTAINS WHEAT, MILK, SOYA, BARLEY AND SULPHITE.",
mainimage: "images/chocochip.webp",
subimage: ["images/chocochip.webp", "images/chocochip1.webp", "images/chocochip2.webp","images/chocochip3.webp"],
  },
  {
id :"b9",
name:"oats",
category: "Snacks",
company: "Britania",
price: 100,
quantity:"100g",
display: "listingpage",
selflife:"1 year",
description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
keyfeature:"Goodness of Wheat: Healthy digestive biscuit with rich blend of wheat (atta) flour and wheat branHi Fibre: Contains high dietary fibre that aids digestive health. A healthy snacking option for anytime.Zero Trans Fat: Contains no trans-fat.",
ingredient:"WHEAT FLOUR (ATTA) (63%), REFINED PALM OIL, SUGAR, WHEAT |BRAN (4.7%), LIQUID GLUCOSE, MILK SOLIDS, MALTODEXTRIN,RAISING AGENTS (500i) & 503(iil], I0DISED SALT, EMULSIFIERS[322(i), 471 & 472¢], NATURAL, NATURE IDENTICAL & ARTIFICIAL(VANILLA) FLAVOURING SUBSTANCES, MALT EXTRACT ANDDOUGH CONDITIONER (223).(Numbers in brackets as per InternationalNumbering System) |CONTAINS WHEAT, MILK, SOYA, BARLEY AND SULPHITE.",
mainimage: "images/cookiesoats.webp",
subimage: ["images/cookiesoats.webp", "images/cookiesoats1.webp", "images/cookiesoats2.webp","images/cookiesoats3.webp"],
  },
  {
id :"b10",
name:"jeera biscuit",
category: "Snacks",
company: "Britania",
price: 100,
quantity:"100g",
display: "listingpage",
selflife:"1 year",
description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
keyfeature:"Goodness of Wheat: Healthy digestive biscuit with rich blend of wheat (atta) flour and wheat branHi Fibre: Contains high dietary fibre that aids digestive health. A healthy snacking option for anytime.Zero Trans Fat: Contains no trans-fat.",
ingredient:"WHEAT FLOUR (ATTA) (63%), REFINED PALM OIL, SUGAR, WHEAT |BRAN (4.7%), LIQUID GLUCOSE, MILK SOLIDS, MALTODEXTRIN,RAISING AGENTS (500i) & 503(iil], I0DISED SALT, EMULSIFIERS[322(i), 471 & 472¢], NATURAL, NATURE IDENTICAL & ARTIFICIAL(VANILLA) FLAVOURING SUBSTANCES, MALT EXTRACT ANDDOUGH CONDITIONER (223).(Numbers in brackets as per InternationalNumbering System) |CONTAINS WHEAT, MILK, SOYA, BARLEY AND SULPHITE.",
mainimage: "images/jeerabiscuit.webp",
subimage: ["images/jeerabiscuit.webp", "images/jeerabiscuit1.webp", "images/jeerabiscuit2.webp","images/jeerabiscuit3.webp"],
  },
  {
id :"b11",
name:"marigold biscuit",
category: "Snacks",
company: "Britania",
price: 100,
quantity:"100g",
display: "listingpage",
selflife:"1 year",
description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
keyfeature:"Goodness of Wheat: Healthy digestive biscuit with rich blend of wheat (atta) flour and wheat branHi Fibre: Contains high dietary fibre that aids digestive health. A healthy snacking option for anytime.Zero Trans Fat: Contains no trans-fat.",
ingredient:"WHEAT FLOUR (ATTA) (63%), REFINED PALM OIL, SUGAR, WHEAT |BRAN (4.7%), LIQUID GLUCOSE, MILK SOLIDS, MALTODEXTRIN,RAISING AGENTS (500i) & 503(iil], I0DISED SALT, EMULSIFIERS[322(i), 471 & 472¢], NATURAL, NATURE IDENTICAL & ARTIFICIAL(VANILLA) FLAVOURING SUBSTANCES, MALT EXTRACT ANDDOUGH CONDITIONER (223).(Numbers in brackets as per InternationalNumbering System) |CONTAINS WHEAT, MILK, SOYA, BARLEY AND SULPHITE.",
mainimage: "images/mariegold.webp",
subimage: ["images/mariegold.webp", "images/mariegold1.webp", "images/mariegold2.webp","images/mariegold3.webp"],
  },
  {
id :"b12",
name:"milano biscuit",
category: "Snacks",
company: "Britania",
price: 100,
quantity:"100g",
display: "listingpage",
selflife:"1 year",
description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
keyfeature:"Goodness of Wheat: Healthy digestive biscuit with rich blend of wheat (atta) flour and wheat branHi Fibre: Contains high dietary fibre that aids digestive health. A healthy snacking option for anytime.Zero Trans Fat: Contains no trans-fat.",
ingredient:"WHEAT FLOUR (ATTA) (63%), REFINED PALM OIL, SUGAR, WHEAT |BRAN (4.7%), LIQUID GLUCOSE, MILK SOLIDS, MALTODEXTRIN,RAISING AGENTS (500i) & 503(iil], I0DISED SALT, EMULSIFIERS[322(i), 471 & 472¢], NATURAL, NATURE IDENTICAL & ARTIFICIAL(VANILLA) FLAVOURING SUBSTANCES, MALT EXTRACT ANDDOUGH CONDITIONER (223).(Numbers in brackets as per InternationalNumbering System) |CONTAINS WHEAT, MILK, SOYA, BARLEY AND SULPHITE.",
mainimage: "images/milano.webp",
subimage: ["images/milano.webp", "images/milano1.webp", "images/milano2.webp","images/milano3.webp"],
  },
  {
id :"b13",
name:"nutrichoice biscuit",
category: "Snacks",
company: "Britania",
price: 100,
quantity:"100g",
display: "listingpage",
selflife:"1 year",
description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
keyfeature:"Goodness of Wheat: Healthy digestive biscuit with rich blend of wheat (atta) flour and wheat branHi Fibre: Contains high dietary fibre that aids digestive health. A healthy snacking option for anytime.Zero Trans Fat: Contains no trans-fat.",
ingredient:"WHEAT FLOUR (ATTA) (63%), REFINED PALM OIL, SUGAR, WHEAT |BRAN (4.7%), LIQUID GLUCOSE, MILK SOLIDS, MALTODEXTRIN,RAISING AGENTS (500i) & 503(iil], I0DISED SALT, EMULSIFIERS[322(i), 471 & 472¢], NATURAL, NATURE IDENTICAL & ARTIFICIAL(VANILLA) FLAVOURING SUBSTANCES, MALT EXTRACT ANDDOUGH CONDITIONER (223).(Numbers in brackets as per InternationalNumbering System) |CONTAINS WHEAT, MILK, SOYA, BARLEY AND SULPHITE.",
mainimage: "images/nutrichoice.webp",
subimage: ["images/nutrichoice.webp", "images/nutrichoice1.webp", "images/nutrichoice2.webp","images/nutrichoice3.webp"],
  },
  {
    id :"b14",
    name:"nutrichoice biscuit",
    category: "Snacks",
    company: "Britania",
    price: 100,
    quantity:"100g",
    display: "listingpage",
    selflife:"1 year",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    keyfeature:"Goodness of Wheat: Healthy digestive biscuit with rich blend of wheat (atta) flour and wheat branHi Fibre: Contains high dietary fibre that aids digestive health. A healthy snacking option for anytime.Zero Trans Fat: Contains no trans-fat.",
    ingredient:"WHEAT FLOUR (ATTA) (63%), REFINED PALM OIL, SUGAR, WHEAT |BRAN (4.7%), LIQUID GLUCOSE, MILK SOLIDS, MALTODEXTRIN,RAISING AGENTS (500i) & 503(iil], I0DISED SALT, EMULSIFIERS[322(i), 471 & 472¢], NATURAL, NATURE IDENTICAL & ARTIFICIAL(VANILLA) FLAVOURING SUBSTANCES, MALT EXTRACT ANDDOUGH CONDITIONER (223).(Numbers in brackets as per InternationalNumbering System) |CONTAINS WHEAT, MILK, SOYA, BARLEY AND SULPHITE.",
    mainimage: "images/vanilacreambiscuit.webp",
    subimage: ["images/vanilacreambiscuit.webp", "images/vanilacreambiscuit1.webp", "images/vanilacreambiscuit2.webp","images/vanilacreambiscuit3.webp"],
      },
      {
        id :"b15",
        name:"nutrichoice biscuit",
        category: "Snacks",
        company: "Britania",
        price: 100,
        quantity:"100g",
        display: "listingpage",
        selflife:"1 year",
        description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
        keyfeature:"Goodness of Wheat: Healthy digestive biscuit with rich blend of wheat (atta) flour and wheat branHi Fibre: Contains high dietary fibre that aids digestive health. A healthy snacking option for anytime.Zero Trans Fat: Contains no trans-fat.",
        ingredient:"WHEAT FLOUR (ATTA) (63%), REFINED PALM OIL, SUGAR, WHEAT |BRAN (4.7%), LIQUID GLUCOSE, MILK SOLIDS, MALTODEXTRIN,RAISING AGENTS (500i) & 503(iil], I0DISED SALT, EMULSIFIERS[322(i), 471 & 472¢], NATURAL, NATURE IDENTICAL & ARTIFICIAL(VANILLA) FLAVOURING SUBSTANCES, MALT EXTRACT ANDDOUGH CONDITIONER (223).(Numbers in brackets as per InternationalNumbering System) |CONTAINS WHEAT, MILK, SOYA, BARLEY AND SULPHITE.",
        mainimage: "images/waffer.webp",
        subimage: ["images/waffer.webp", "images/waffer1.webp", "images/waffer2.webp","images/waffer3.webp"],
          },
  {
    id:"c1",
    name: "Lay's Chilli  ",
    category: "Chips",
      company: "Lay's",
    price: 40,
    quantity:"25 g",
    flavour:"Chilli",
    display: "mainpage",
    selflife:"12 months",
    keyfeature:"Wholesome taste Healthy and nutritious milkRich in calcium",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    ingredient:"Lay’s West Indies Hot 'n' Sweet Chilli flavour will ignite your tastebuds.Made from the highest quality, farm-grown potatoes.Lay’s West Indies Hot 'n' Sweet Chilli is a 100% vegetarian snack.A versatile snack that can be enjoyed in any setting.Lay’s is always on the lookout for the best flavours, cuts, and innovations that are guaranteed to bring a smile to your face.",
    mainimage: "images/lays.webp",
    subimage: ["images/lays.webp", "images/lays1.webp", "images/lays2.webp","images/lays3.webp"],
  },
  {
    id:"c2",
    name: "Doritos Cheese Nachos",
    category: "Chips",
      company: "Doritos",
    price: 40,
    quantity:"40 g",
    display: "mainpage",
    selflife:"12 months",
    keyfeature:"Wholesome taste Healthy and nutritious milkRich in calcium",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    ingredient:"Lay’s West Indies Hot 'n' Sweet Chilli flavour will ignite your tastebuds.Made from the highest quality, farm-grown potatoes.Lay’s West Indies Hot 'n' Sweet Chilli is a 100% vegetarian snack.A versatile snack that can be enjoyed in any setting.Lay’s is always on the lookout for the best flavours, cuts, and innovations that are guaranteed to bring a smile to your face.",
    mainimage: "images/doritos.webp",
    subimage: ["images/doritos.webp", "images/doritos1.webp", "images/doritos2.webp","images/doritos3.webp"],
  },
  {
    id:"c3",
    name: "Pringles Sour  Chips",
    category: "Chips",
      company: "Pringles",
    price: 35,
    quantity:"100 g",
    display: "mainpage",
    selflife:"12 months",
    keyfeature:"Wholesome taste Healthy and nutritious milkRich in calcium",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    ingredient:"Lay’s West Indies Hot 'n' Sweet Chilli flavour will ignite your tastebuds.Made from the highest quality, farm-grown potatoes.Lay’s West Indies Hot 'n' Sweet Chilli is a 100% vegetarian snack.A versatile snack that can be enjoyed in any setting.Lay’s is always on the lookout for the best flavours, cuts, and innovations that are guaranteed to bring a smile to your face.",
    mainimage: "images/prin.webp",
    subimage: ["images/prin.webp", "images/prin1.webp", "images/prin2.webp","images/prin3.webp"],
  },
  {
    id:"c4",
    name: "Lay's Limon  Chips",
    category: "Chips",
      company: "Lay's",
    price: 20,
    quantity:"28 g",
    display: "mainpage",
    selflife:"12 months",
    keyfeature:"Wholesome taste Healthy and nutritious milkRich in calcium",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    ingredient:"Lay’s West Indies Hot 'n' Sweet Chilli flavour will ignite your tastebuds.Made from the highest quality, farm-grown potatoes.Lay’s West Indies Hot 'n' Sweet Chilli is a 100% vegetarian snack.A versatile snack that can be enjoyed in any setting.Lay’s is always on the lookout for the best flavours, cuts, and innovations that are guaranteed to bring a smile to your face.",
    mainimage: "images/layslemon.webp",
    subimage: ["images/layslemon.webp", "images/layslemon1.webp", "images/layslemon2.webp","images/layslemon3.webp"],
  },
  {
    id:"c5",
    name: "Bingo Mad Angles",
    category: "Chips",
      company: "Bingo",
    price: 50,
    quantity:"50 g",
    display: "mainpage",
    selflife:"12 months",
    keyfeature:"Wholesome taste Healthy and nutritious milkRich in calcium",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    ingredient:"Lay’s West Indies Hot 'n' Sweet Chilli flavour will ignite your tastebuds.Made from the highest quality, farm-grown potatoes.Lay’s West Indies Hot 'n' Sweet Chilli is a 100% vegetarian snack.A versatile snack that can be enjoyed in any setting.Lay’s is always on the lookout for the best flavours, cuts, and innovations that are guaranteed to bring a smile to your face.",
    mainimage: "images/bingo.webp",
    subimage: ["images/bingo.webp", "images/bingo1.webp", "images/bingo2.webp","images/bingo3.webp"],
  },
  {
    id:"c6",
    name: "Beyond Banana Chips",
    category: "Chips",
      company: "Beyond Chips",
    price: 30,
    quantity:"100 g",
    display: "mainpage",
    selflife:"12 months",
    keyfeature:"Wholesome taste Healthy and nutritious milkRich in calcium",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    ingredient:"Lay’s West Indies Hot 'n' Sweet Chilli flavour will ignite your tastebuds.Made from the highest quality, farm-grown potatoes.Lay’s West Indies Hot 'n' Sweet Chilli is a 100% vegetarian snack.A versatile snack that can be enjoyed in any setting.Lay’s is always on the lookout for the best flavours, cuts, and innovations that are guaranteed to bring a smile to your face.",
    mainimage: "images/bananachips.webp",
    subimage: ["images/bananachips.webp", "images/bananachips1.webp", "images/bananachips2.webp","images/bananachips3.webp"],
  },
  {
    id:"c7",
    name: "Beyond Snack Chips",
    category: "Chips",
      company: "Beyond Chips",
    price: 10,
    quantity:"70 g",
    display: "mainpage",
    selflife:"12 months",
    keyfeature:"Wholesome taste Healthy and nutritious milkRich in calcium",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    ingredient:"Lay’s West Indies Hot 'n' Sweet Chilli flavour will ignite your tastebuds.Made from the highest quality, farm-grown potatoes.Lay’s West Indies Hot 'n' Sweet Chilli is a 100% vegetarian snack.A versatile snack that can be enjoyed in any setting.Lay’s is always on the lookout for the best flavours, cuts, and innovations that are guaranteed to bring a smile to your face.",
   description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    mainimage: "images/newchips.webp",
    subimage: ["images/newchips.webp", "images/newchips1.webp", "images/newchips2.webp","images/newchips3.webp"],
  },
  {
id:"c8",
    name: "Beyond Snack Chips",
    category: "Chips",
      company: "Beyond Chips",
    price: 10,
    quantity:"70 g",
    display: "listingpage",
    selflife:"12 months",
    keyfeature:"Wholesome taste Healthy and nutritious milkRich in calcium",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    ingredient:"Lay’s West Indies Hot 'n' Sweet Chilli flavour will ignite your tastebuds.Made from the highest quality, farm-grown potatoes.Lay’s West Indies Hot 'n' Sweet Chilli is a 100% vegetarian snack.A versatile snack that can be enjoyed in any setting.Lay’s is always on the lookout for the best flavours, cuts, and innovations that are guaranteed to bring a smile to your face.",
   description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    mainimage: "images/freshchips.webp",
    subimage: ["images/freshchips.webp", "images/freshchips1.webp", "images/freshchips2.webp","images/freshchips3.webp"],
  },{
id:"c9",
    name: "Beyond Snack Chips",
    category: "Chips",
      company: "Beyond Chips",
    price: 10,
    quantity:"70 g",
    display: "listingpage",
    selflife:"12 months",
    keyfeature:"Wholesome taste Healthy and nutritious milkRich in calcium",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    ingredient:"Lay’s West Indies Hot 'n' Sweet Chilli flavour will ignite your tastebuds.Made from the highest quality, farm-grown potatoes.Lay’s West Indies Hot 'n' Sweet Chilli is a 100% vegetarian snack.A versatile snack that can be enjoyed in any setting.Lay’s is always on the lookout for the best flavours, cuts, and innovations that are guaranteed to bring a smile to your face.",
   description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    mainimage: "images/madangle.webp",
    subimage: ["images/madangle.webp", "images/madangle1.webp", "images/madangle2.webp","images/madangle3.webp"],
  },
  {
id:"c10",
    name: "Beyond Snack Chips",
    category: "Chips",
      company: "Beyond Chips",
    price: 10,
    quantity:"70 g",
    display: "listingpage",
    selflife:"12 months",
    keyfeature:"Wholesome taste Healthy and nutritious milkRich in calcium",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    ingredient:"Lay’s West Indies Hot 'n' Sweet Chilli flavour will ignite your tastebuds.Made from the highest quality, farm-grown potatoes.Lay’s West Indies Hot 'n' Sweet Chilli is a 100% vegetarian snack.A versatile snack that can be enjoyed in any setting.Lay’s is always on the lookout for the best flavours, cuts, and innovations that are guaranteed to bring a smile to your face.",
   description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    mainimage: "images/potatopepper.webp",
    subimage: ["images/potatopepper.webp", "images/potatopepper1.webp", "images/potatopepper2.webp","images/potatopepper2.webp"],
  },
  {
id:"c11",
    name: "Beyond Snack Chips",
    category: "Chips",
      company: "Beyond Chips",
    price: 10,
    quantity:"70 g",
    display: "listingpage",
    selflife:"12 months",
    keyfeature:"Wholesome taste Healthy and nutritious milkRich in calcium",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    ingredient:"Lay’s West Indies Hot 'n' Sweet Chilli flavour will ignite your tastebuds.Made from the highest quality, farm-grown potatoes.Lay’s West Indies Hot 'n' Sweet Chilli is a 100% vegetarian snack.A versatile snack that can be enjoyed in any setting.Lay’s is always on the lookout for the best flavours, cuts, and innovations that are guaranteed to bring a smile to your face.",
   description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    mainimage: "images/purpledoritos.webp",
    subimage: ["images/purpledoritos.webp", "images/purpledoritos1.webp", "images/purpledoritos2.webp","images/purpledoritos3.webp"],
  },
  {
id:"c12",
    name: "Beyond Snack Chips",
    category: "Chips",
      company: "Beyond Chips",
    price: 10,
    quantity:"70 g",
    display: "listingpage",
    selflife:"12 months",
    keyfeature:"Wholesome taste Healthy and nutritious milkRich in calcium",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    ingredient:"Lay’s West Indies Hot 'n' Sweet Chilli flavour will ignite your tastebuds.Made from the highest quality, farm-grown potatoes.Lay’s West Indies Hot 'n' Sweet Chilli is a 100% vegetarian snack.A versatile snack that can be enjoyed in any setting.Lay’s is always on the lookout for the best flavours, cuts, and innovations that are guaranteed to bring a smile to your face.",
   description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    mainimage: "images/wikedchips.webp",
    subimage: ["images/wikedchips.webp", "images/wikedchips1.webp", "images/wikedchips2.webp","images/wikedchips3.webp"],
  },
  {
id:"c13",
    name: "Beyond Snack Chips",
    category: "Chips",
      company: "Beyond Chips",
    price: 10,
    quantity:"70 g",
    display: "listingpage",
    selflife:"12 months",
    keyfeature:"Wholesome taste Healthy and nutritious milkRich in calcium",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    ingredient:"Lay’s West Indies Hot 'n' Sweet Chilli flavour will ignite your tastebuds.Made from the highest quality, farm-grown potatoes.Lay’s West Indies Hot 'n' Sweet Chilli is a 100% vegetarian snack.A versatile snack that can be enjoyed in any setting.Lay’s is always on the lookout for the best flavours, cuts, and innovations that are guaranteed to bring a smile to your face.",
   description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    mainimage: "images/periperichips.webp",
    subimage: ["images/periperichips.webp", "images/periperichips1.webp", "images/periperichips2.webp","images/periperichips3.webp"],
  },
  {
id:"c14",
    name: "Beyond Snack Chips",
    category: "Chips",
      company: "Beyond Chips",
    price: 10,
    quantity:"70 g",
    display: "listingpage",
    selflife:"12 months",
    keyfeature:"Wholesome taste Healthy and nutritious milkRich in calcium",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    ingredient:"Lay’s West Indies Hot 'n' Sweet Chilli flavour will ignite your tastebuds.Made from the highest quality, farm-grown potatoes.Lay’s West Indies Hot 'n' Sweet Chilli is a 100% vegetarian snack.A versatile snack that can be enjoyed in any setting.Lay’s is always on the lookout for the best flavours, cuts, and innovations that are guaranteed to bring a smile to your face.",
   description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    mainimage: "images/ragichips.webp",
    subimage: ["images/ragichips.webp", "images/ragichips1.webp", "images/ragichips2.webp","images/ragichips3.webp"],
  },
  {
id:"c15",
    name: "Beyond Snack Chips",
    category: "Chips",
      company: "Beyond Chips",
    price: 10,
    quantity:"70 g",
    display: "listingpage",
    selflife:"12 months",
    keyfeature:"Wholesome taste Healthy and nutritious milkRich in calcium",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    ingredient:"Lay’s West Indies Hot 'n' Sweet Chilli flavour will ignite your tastebuds.Made from the highest quality, farm-grown potatoes.Lay’s West Indies Hot 'n' Sweet Chilli is a 100% vegetarian snack.A versatile snack that can be enjoyed in any setting.Lay’s is always on the lookout for the best flavours, cuts, and innovations that are guaranteed to bring a smile to your face.",
   description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    mainimage: "images/nachochips.webp",
    subimage: ["images/nachochips.webp", "images/nachochips1.webp", "images/nachochips2.webp","images/nachochips3.webp"],
  },
{
    id:"d1" ,
    name: " Tata Tea Gold",
    category: "Tea",
      company: "Tata Tea",
    
    price: 200,
    quantity:"200 g",
    display: "mainpage",
    selflife:"12 months",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    ingredient:"Black Tea",
    mainimage: "images/goldtea.webp",
    subimage: ["images/goldtea.webp", "images/goldtea1.webp", "images/goldtea2.webp","images/goldtea3.webp"],
},
{
    id:"d2" ,
    name: "Tata Agni  Tea",
    category: "Tea",
      company: "Tata Tea",
    price: 50,
    quantity:"100 g",
    display: "mainpage",
    selflife:"12 months",
    ingredient:"Black Tea",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    mainimage: "images/aginitea.webp",
    subimage: ["images/aginitea.webp", "images/aginitea1.webp", "images/aginitea2.webp","images/aginitea3.webp"],
},
{
    id:"d3" ,
    name: "Tata Grand Coffee",
    category: "Tea",
      company: "Tata Tea",
    price: 200,
    quantity:"400 g",
    display: "mainpage",
    selflife:"12 months",
    ingredient:"Black Tea",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    mainimage: "images/tatacoffe.webp",
    subimage: ["images/tatacoffe.webp", "images/tatacoffe1.webp", "images/tatacoffe12.webp","images/tatacoffe13.webp"],
   
},
{
    id:"d4" ,
    name: "Lipton Green Tea ",
    category: "Tea",
      company: "Lipton",
    price: 250,
    quantity:"500 g",
    display: "mainpage",
    selflife:"12 months",
    ingredient:"Black Tea",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    mainimage: "images/lipton.webp",
    subimage: ["images/lipton.webp", "images/lipton1.webp", "images/lipton2.webp","images/lipton3.webp"],
},
{
    id:"d5" ,
    name: "Tata Premium Tea ",
    category: "Tea",
    price: 150,
      company: "Tata Tea",
    quantity:"250 g",
    selflife:"12 months",
    display: "mainpage",
    ingredient:"Black Tea",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    mainimage: "images/tatatea1.webp",
    subimage: ["images/tatatea1.webp", "images/tatatea1.webp", "images/tatatea2.webp","images/tatatea3.webp"],
},
{
    id:"d6" ,
    name: "Nescafe Coffee Powder ",
    category: "Tea",
    price: 250,
    quantity:"800 g",
      company: "Nescafe",
    selflife:"12 months",
    display: "mainpage",
    ingredient:"Black Tea",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    mainimage: "images/coffe.webp",
    subimage: ["images/coffe.webp", "images/coffe1.webp", "images/coffe2.webp","images/coffe3.webp"],
},
{
    id:"d7" ,
    name: "TataElaichi Tea",
    category: "Tea",
      company: "Tata Tea",
    price: 80,
    quantity:"100 g",
    display: "mainpage",
    selflife:"12 months",
    description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
    ingredient:"Black Tea",
    mainimage: "images/elachitea.webp",
    subimage: ["images/elachitea.webp", "images/elachitea1.webp", "images/elachitea2.webp","images/elachitea3.webp"],
},
{
id:"e1",
name: "Ice Cream",
category: "IceCream",
  company: "Amul",
price: 80,
quantity:"100 g",
display: "listingpage",
selflife:"12 months",
description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
ingredient:"Black Tea",
mainimage:  "images/icecreame1.webp",
subimage: ["images/icecreame1.webp", "images/icecreame2.webp", "images/icecreame3.webp","images/icecreame4.webp"],
},
{
  id:"e2",
  name: "Ice Cream",
  category: "IceCream",
    company: "Amul",
  price: 80,
  quantity:"100 g",
  display: "listingpage",
  selflife:"12 months",
  description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
  ingredient:"Black Tea",
  mainimage: "images/icecreame2.webp",
  subimage: ["images/icecreame2.webp", "images/icecreame21.webp", "images/icecreame12.webp","images/icecreame23.webp"],
  },
{
  id:"e3",
  name: "Ice Cream",
  category: "IceCream",
    company: "Amul",
  price: 80,
  quantity:"100 g",
  display: "listingpage",
  selflife:"12 months",
  description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
  ingredient:"Black Tea",
  mainimage: "images/icecreame3.webp",
  subimage: ["images/icecreame1.webp", "images/icecreame31.webp", "images/icecreame32.webp","images/icecreame33.webp"],
  },
{
  id:"e4",
  name: "Ice Cream",
  category: "IceCream",
    company: "Amul",
  price: 80,
  quantity:"100 g",
  display: "listingpage",
  selflife:"12 months",
  description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
  ingredient:"Black Tea",
  mainimage: "images/icecreame4.webp",
  subimage: ["images/icecreame4.webp", "images/icecreame41.webp", "images/icecreame42.webp","images/icecreame43.webp"],
  },
{
  id:"e5",
  name: "Ice Cream",
  category: "IceCream",
    company: "Amul",
  price: 80,
  quantity:"100 g",
  display: "listingpage",
  selflife:"12 months",
  description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
  ingredient:"Black Tea",
  mainimage: "images/icecreame5.webp",
  subimage: ["images/icecreame5.webp", "images/icecreame51.webp", "images/icecreame52.webp","images/icecreame53.webp"],
  },
{
  id:"e6",
  name: "Ice Cream",
  category: "IceCream",
    company: "Amul",
  price: 80,
  quantity:"100 g",
  display: "listingpage",
  selflife:"12 months",
  description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
  ingredient:"Black Tea",
  mainimage: "images/icecreame6.webp",
  subimage: ["images/icecreame6.webp", "images/icecreame61.webp", "images/icecreame62.webp","images/icecreame63.webp"],
  },
{
  id:"e7",
  name: "Ice Cream",
  category: "IceCream",
    company: "Amul",
  price: 80,
  quantity:"100 g",
  display: "listingpage",
  selflife:"12 months",
  description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
  ingredient:"Black Tea",
  mainimage: "images/icecreame7.webp",
  subimage: ["images/icecreame7.webp", "images/icecreame71.webp", "images/icecreame72.webp","images/icecreame73.webp"],
  },
{
  id:"e8",
  name: "Ice Cream",
  category: "IceCream",
    company: "Amul",
  price: 80,
  quantity:"100 g",
  display: "listingpage",
  selflife:"12 months",
  description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
  ingredient:"Black Tea",
  mainimage: "images/icecreame8.webp",
  subimage: ["images/icecreame8.webp", "images/icecreame81.webp", "images/icecreame82.webp","images/icecreame83.webp"],
  },
{
  id:"e9",
  name: "Ice Cream",
  category: "IceCream",
    company: "Amul",
  price: 80,
  quantity:"100 g",
  display: "listingpage",
  selflife:"12 months",
  description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
  ingredient:"Black Tea",
  mainimage: "images/icecreame9.webp",
  subimage: ["images/icecreame9.webp", "images/icecreame91.webp", "images/icecreame92.webp","images/icecreame93.webp"],
  },
{
  id:"e10",
  name: "Ice Cream",
  category: "IceCream",
    company: "Amul",
  price: 80,
  quantity:"100 g",
  display: "listingpage",
  selflife:"12 months",
  description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
  ingredient:"Black Tea",
  mainimage: "images/icecreame10.webp",
  subimage: ["images/icecreame10.webp", "images/icecreame101.webp", "images/icecreame102.webp","images/icecreame103.webp"],
  },
{
  id:"e11",
  name: "Ice Cream",
  category: "IceCream",
    company: "Amul",
  price: 80,
  quantity:"100 g",
  display: "listingpage",
  selflife:"12 months",
  description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
  ingredient:"Black Tea",
  mainimage: "images/icecreame111.webp",
  subimage: ["images/icecreame111.webp", "images/icecreame112.webp", "images/icecreame113.webp","images/icecreame112.webp"],
  },
{
  id:"e12",
  name: "Ice Cream",
  category: "IceCream",
    company: "Amul",
  price: 80,
  quantity:"100 g",
  display: "listingpage",
  selflife:"12 months",
  description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
  ingredient:"Black Tea",
  mainimage: "images/icecreame121.webp",
  subimage: ["images/icecreame121.webp", "images/icecreame122.webp", "images/icecreame123.webp","images/icecreame124.webp"],
  },
{
  id:"e13",
  name: "Ice Cream",
  category: "IceCream",
    company: "Amul",
  price: 80,
  quantity:"100 g",
  display: "listingpage",
  selflife:"12 months",
  description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
  ingredient:"Black Tea",
  mainimage: "images/icecreame121.webp",
  subimage: ["images/icecreame121.webp", "images/icecreame122.webp", "images/icecreame123.webp","images/icecreame124.webp"],
  },
{
  id:"e14",
  name: "Ice Cream",
  category: "IceCream",
    company: "Amul",
  price: 80,
  quantity:"100 g",
  display: "listingpage",
  selflife:"12 months",
  description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
  ingredient:"Black Tea",
  mainimage: "images/icecreame111.webp",
  subimage: ["images/icecreame111.webp", "images/icecreame112.webp", "images/icecreame113.webp","images/icecreame112.webp"],
  },
{
  id:"e1",
  name: "Ice Cream",
  category: "IceCream",
    company: "Amul",
  price: 80,
  quantity:"100 g",
  display: "listingpage",
  selflife:"12 months",
  description:"Made from the freshest of cream, the Amul butter has wonderful taste which is delicate and slightly salty. This finely processed butter is natural, pure and tastes best with toasts and sandwiches. Has a natural and pure formulation that gives a great taste. Made from fresh cream that has a delicious flavour. Spread it over toast or cook your curries in it for a heavenly taste.",
  ingredient:"Black Tea",
  mainimage: "images/icecreame7.webp",
  subimage: ["images/icecreame7.webp", "images/icecreame71.webp", "images/icecreame72.webp","images/icecreame73.webp"],
  },

];
